### ISSUE TITLE
Suggestion: add -X, -Y, -Z to negative axes on viewport gizmo

### ISSUE THREAD

**Issue by jdegenstein** [yeicor-3d/yet-another-cad-viewer#173]
I think it would be valuable to label the negative axes with e.g. "-X" as well. When looking at the negative axes it makes it a bit clearer what view is being used.

![image](https://github.com/user-attachments/assets/ac0e6fe4-ea60-470d-99e4-b66f3b05838c)

used this tool to test https://fennec-hub.github.io/three-viewport-gizmo/#/config

and exported to the attached config file:
[orientation_gizmo.json](https://github.com/user-attachments/files/17120313/orientation_gizmo.json)

**Comment by Yeicor** [comment]
Implemented in b2f9880fd06bafc8f5d232e43114f62ed9aa2b99 and released in v0.8.11. Thanks for looking into it.

**Comment by jdegenstein** [comment]
Thank you!
